/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "getinf.h"
#define MAX 512

char *itoa(int i, char b[]) {
  char const digit[] = "0123456789";
  char *p = b;
  if (i < 0) {
    *p++ = '-';
    i *= -1;
  }
  int shifter = i;
  do {  // Move to where representation ends
    ++p;
    shifter = shifter / 10;
  } while (shifter);
  *p = '\0';
  do {  // Move back, inserting digits as u go
    *--p = digit[i % 10];
    i = i / 10;
  } while (i);
  return b;
}

Msg *getmsg_1_svc(int *argp, struct svc_req *rqstp) {
  static Msg result = 0;
  static int counter;
  // char buf[MAX];

  //  * insert server code here

  // *result = 1;
  // strcat(result, " 44444 ");
  // itoa(counter, buf);
  // strcat(message, buf);
  *result++;

  return &result;
}
