/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "getinf.h"

int *getmsg_1_svc(int *argp, struct svc_req *rqstp) {
  static int result;

  /*
   * insert server code here
   */

  result++;

  return &result;
}
