/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COUNTER_H_RPCGEN
#define _COUNTER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define Counter 0x21272060
#define Ver1 1

#if defined(__STDC__) || defined(__cplusplus)
#define next 1
extern  void * next_1(void *, CLIENT *);
extern  int * next_1_svc(void *, struct svc_req *);
extern int counter_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define next 1
extern  void * next_1();
extern  void * next_1_svc();
extern int counter_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COUNTER_H_RPCGEN */
