/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "getinf.h"

static int counter =0;

int * getmsg_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;	
	result = counter;
	counter++;

	return &result;
}
