/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "getinf.h"

void getinf_1(char *host) {
  CLIENT *clnt;
  Msg *result_1;
  int getmsg_1_arg = 127206;

#ifndef DEBUG
  clnt = clnt_create(host, GETINF, Ver1, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  result_1 = getmsg_1(&getmsg_1_arg, clnt);
  if (result_1 == (Msg *)NULL) {
    clnt_perror(clnt, "call failed");
  } else {
    printf("Result: %s\n", *result_1);
  }
#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
  char *host;

  if (argc < 2) {
    printf("usage: %s server_host\n", argv[0]);
    exit(1);
  }
  host = argv[1];
  getinf_1(host);
  exit(0);
}
