/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GETINF_H_RPCGEN
#define _GETINF_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *Msg;

#define GETINF 0x21000000
#define Ver1 1

#if defined(__STDC__) || defined(__cplusplus)
#define getmsg 1
extern  Msg * getmsg_1(int *, CLIENT *);
extern  Msg * getmsg_1_svc(int *, struct svc_req *);
extern int getinf_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getmsg 1
extern  Msg * getmsg_1();
extern  Msg * getmsg_1_svc();
extern int getinf_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Msg (XDR *, Msg*);

#else /* K&R C */
extern bool_t xdr_Msg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GETINF_H_RPCGEN */
