/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "getinf.h"

Msg *
getmsg_1_svc(int *argp, struct svc_req *rqstp)
{
	static Msg  result;

	result = "Serwus";

	return &result;
}
